grafana:
  service:
    type: ClusterIP
  persistence:
    enabled: false
  rbac:
    create: true
    pspEnabled: false
    namespaced: true
  serviceAccount:
    create: true
    name: grafana
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
    datasources:
      enabled: true
      label: grafana_datasource
  configDashboardProviders:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
