apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "hello-world.name" . }}
